### PR TITLE
Adding typeahead-focus-first=false option

### PR DESCRIPTION
**Pull request by robbse**
Added typeahead-focus-first option from angular-bootstrap

### CODE REVIEW

**Comment by jstoneky** [comment]
+1 - please merge ;)

**Comment by kdschaffe** [comment]
+1

**Comment by PeteAshworth** [comment]
+1

**Comment by pchoi** [comment]
+1, can we please get this feature merged?

**Comment by alindber** [comment]
+1 - would like to have this merged

**Comment by Leocrest** [comment]
+1 Ya this would be great

**Comment by jbrowning** [comment]
👍  LGTM. Thanks!

**Pull request merged**
